[package]
name = "lieutenant"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
lieutenant-macros = { path =  "macros" }

anyhow = "1.0"
slab = "0.4"
smallvec = "1.4"
bstr = "0.2"

[dev-dependencies]
once_cell = "1.3"

[workspace]
members = [".", "macros"]
